### ISSUE TITLE
Qst

### ISSUE THREAD

**Issue by hao091012** [severinEvo/gene_expression#2]
Dear all,
I am interested in Pst calculation. I read your very excellent paper published in Molecular Ecology (2016)(Divergence in gene expression within and between two closely related flycatcher species.) 
According to your paper, there was a code for Pst calculation. But I only find Qst.R script. I have no idea whether Qst is Pst as your work used. And if I used Qst.R to my data. I got many negative Pst, vW, vB values for many genes, is it suitable? Within population, is there a higher genetic variance than between population? How about your genes? Have you encountered a similar situation? 
Could you please give me some suggestion?

Looking forward for your reply. Thanks in advance.

Best
Yan

**Comment by severinEvo** [comment]
Hi Yan,

Thank you for you interest in my paper and my scripts.

The difference between *P*<sub>ST</sub> and *Q*<sub>ST</sub> is that in *Q*<sub>ST</sub>, the additive genetic variance is estimated in from data acquired from a genetic cross, which is difficult to establish for a number of organisms, including flycatchers. An easy way to get around this problem is to approximate the variance using the phenotypic variance, an approach that has been termed *P*<sub>ST</sub>. The calculation of *Q*<sub>ST</sub> and *P*<sub>ST</sub> is very similar; the only difference is where the variance comes from. The variance in my *Q*<sub>ST</sub> formula is estimated from the gene expression input data, which means that it is, in fact, *P*<sub>ST</sub>, and not *Q*<sub>ST</sub>! The reason the script is named *Q*<sub>ST</sub> is that I learned about this fact afterwards.

Using this formula, slightly negative values for *P*<sub>ST</sub>, *v*<sub>W</sub>, and *v*<sub>B</sub> are not uncommon. Some people like to constrain *Q*<sub>ST</sub> at 0 to avoid this, but doing so will change the distribution of the values and correlations are better done on data that is not bound by 0, but that extends into the negative. This is why I implemented the formula as is. If you do not like this behaviour, you can change the script by hand. You can also look up the previous version of this code, which included the constraint.

In my experience, it is most common that the within-population variance *v*<sub>W</sub> is larger than the between-population variance *v*<sub>B</sub>. I think that is to be expected, given that gene expression values essentially range on a linear scale between "low expression" and "high expression," with high expression even being costly. In contrast, many other phenotypic characters can have multiple axes of phenotypic range. This somewhat reduced range of gene expression phenotypic variation leads to the observation that *v*<sub>W</sub> is most often larger than *v*<sub>B</sub>. I have attached a real data plot showing two examples, one rare example of a gene with a much larger *v*<sub>B</sub> than *v*<sub>W</sub>, and an example of the very common case of genes with a larger *v*<sub>W</sub> than *v*<sub>B</sub>, which should illustrate the point. (In this case, *Q*<sub>ST</sub> is in fact negative and not "= 0" using the updated script.)

I hope this helps. My best wishes!

![150521_berkeley](https://user-images.githubusercontent.com/12732754/29874140-df63e764-8d63-11e7-9cce-912e4e7b9c24.png)

**Comment by severinEvo** [comment]
Hi Yan,

I have now changed the name of the script to *P*<sub>ST</sub>. I have also added some info about the questions you had to the README.

Thank you for your input!

**Comment by hao091012** [comment]
Thank you so much, Severin! It's very helpful for me. But sorry to bother you again with another question. 
I am very confused by PstDE determination. You said "Differentially expressed (DE) genes were determined using 1000 resampled replicates per organ, and P-values were resampling corrected according to Phipson & Smyth (2010).", it put me at a loss because if we sampled some genes with low Pst value, how can we call them DEG? I know maybe I don't understand this correctly. And could you give me some suggestion for PstDE selection?

Thanks again. 

Sincerely
Yan

**Comment by severinEvo** [comment]
Hi Yan,

I performed resampling as a permutation test. For each gene, if there are, say, 10 samples from group A and 10 samples from group B, I sampled 10 of the total 20 sampled at random and called them "A", and tested against the remaining 10 samples, calling them "B." Repeating this procedure 1000 times, I got a null distribution for *P*<sub>ST</sub> that I compared to my actual *P*<sub>ST</sub> values. If the actual value was significantly larger than the resampled value, I called the gene DE. A gene with a low *P*<sub>ST</sub> value will rarely ever be significant, but there might be a few. I used Phipson & Smyth 2010 to correct for cases when the *P* value was 0 or 1.

As this is not about the actual *P*<sub>ST</sub> script any longer, I will close this thread now. Feel free to reach out to me at severin.uebbing-ät'yale.edu if you have further questions!

**Comment by hao091012** [comment]
Got it, thank you so much again. Ok, if I have any other question, I'll send you an email. Thanks again.

**Comment by hao091012** [comment]
Hi, Severin
When I check the "Spearman rank correlations (rho) of PST and its variance components with expression specificity (tau)" in my data, I got totally accordantly negative correlations among Pst, variance within species and between species. But in yours, there were mostly positive correlations. 
What do you think about this?

Best~


haoyan14@mails.ucas.ac.cn
 
From: severinEvo
Date: 2017-08-30 23:56
To: severinEvo/gene_expression
CC: hao091012; Author
Subject: Re: [severinEvo/gene_expression] Qst (#2)
Closed #2.
